services:
  postgres:
    image: postgres:16
    container_name: sr4s-postgres
    restart: always
    environment:
      POSTGRES_USER: sr4s
      POSTGRES_PASSWORD: sr4s
      POSTGRES_DB: sr4s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: sr4s-adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"


volumes:
  postgres_data: